version: '3.9'

services:
  app:
    image: httpd:latest
    container_name: my-apache-app
    restart: always
    ports:
    - '80:80'
    volumes:
    - ./index.html:/usr/local/apache2/htdocs/index.html
